//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chattingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIFTY
    {
        public int NIFTY_ID { get; set; }
        public string OI { get; set; }
        public string Chng_In_OI { get; set; }
        public string Volume { get; set; }
        public string IV { get; set; }
        public string LTP { get; set; }
        public string Net_Ching { get; set; }
        public string Bid_Qty { get; set; }
        public string Bid_Price { get; set; }
        public string Ask_Price { get; set; }
        public string Ask_Qty { get; set; }
        public string Strike_Price { get; set; }
        public string Bid_Qty1 { get; set; }
        public string Bid_Price1 { get; set; }
        public string Ask_Price1 { get; set; }
        public string Ask_Qty1 { get; set; }
        public string Net_Ching1 { get; set; }
        public string LTP1 { get; set; }
        public string IV1 { get; set; }
        public string Volume1 { get; set; }
        public string Chng_In_OI1 { get; set; }
        public string OI1 { get; set; }
        public string Spotprice { get; set; }
        public string Date { get; set; }
    }
}
